# this is the build file for project 
# it is autogenerated by the xmake build system.
# do not edit by hand.

ifneq ($(VERBOSE),1)
VV=@
endif

CCACHE=/usr/bin/ccache
CU=/usr/bin/clang
FC=/usr/bin/gfortran
GC=/usr/bin/go
MM=/usr/bin/gcc
CXX=/usr/bin/gcc
ZC=/usr/bin/zig
CC=/usr/bin/gcc
MXX=/usr/bin/gcc
AS=/usr/bin/gcc
RC=/usr/bin/rustc

FCSH=/usr/bin/gfortran
SH=/usr/bin/g++
RCSH=/usr/bin/rustc
ZCSH=/usr/bin/zig
FCLD=/usr/bin/gfortran
LD=/usr/bin/g++
RCLD=/usr/bin/rustc
ZCLD=/usr/bin/zig
GCLD=/usr/bin/go
AR=/usr/bin/ar
RCAR=/usr/bin/rustc
ZCAR=/usr/bin/zig
GCAR=/usr/bin/go

main_LD=/usr/bin/clang++
main_CXX=/usr/bin/clang
main_CXX=/usr/bin/clang

main_CXXFLAGS=-Qunused-arguments -m64 -g -Wall -Werror -O0 -std=c++20 -I/usr/include -I/usr/local/include -Iinclude -D__PROJECT_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp\" "-D__OS__=\"linux\" " -D__DATA_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp/data/\" -D__CONFIG_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp/config/\" -isystem /home/luoyebai/.xmake/packages/g/gtest/v1.14.0/f970d73ab5f14d76aa4b780b603d9493/include -isystem /usr/include/opencv4 -isystem /usr/include/gtk-3.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/freetype2 -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/harfbuzz -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/libpng16 -isystem /usr/include/pixman-1 -isystem /usr/include/cloudproviders -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/dbus-1.0/include -isystem /usr/include/fribidi -isystem /usr/include/sysprof-6 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/libdrm -pthread -fsanitize=address
main_CXXFLAGS=-Qunused-arguments -m64 -g -Wall -Werror -O0 -std=c++20 -I/usr/include -I/usr/local/include -Iinclude -D__PROJECT_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp\" "-D__OS__=\"linux\" " -D__DATA_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp/data/\" -D__CONFIG_DIR__=\"/home/luoyebai/workspace/project/face_recognition_sface/cpp/config/\" -isystem /home/luoyebai/.xmake/packages/g/gtest/v1.14.0/f970d73ab5f14d76aa4b780b603d9493/include -isystem /usr/include/opencv4 -isystem /usr/include/gtk-3.0 -isystem /usr/include/pango-1.0 -isystem /usr/include/cairo -isystem /usr/include/gdk-pixbuf-2.0 -isystem /usr/include/atk-1.0 -isystem /usr/include/freetype2 -isystem /usr/include/glib-2.0 -isystem /usr/lib/glib-2.0/include -isystem /usr/include/harfbuzz -isystem /usr/include/libmount -isystem /usr/include/blkid -isystem /usr/include/libpng16 -isystem /usr/include/pixman-1 -isystem /usr/include/cloudproviders -isystem /usr/include/at-spi2-atk/2.0 -isystem /usr/include/at-spi-2.0 -isystem /usr/include/dbus-1.0 -isystem /usr/lib/dbus-1.0/include -isystem /usr/include/fribidi -isystem /usr/include/sysprof-6 -isystem /usr/include/gio-unix-2.0 -isystem /usr/include/libdrm -pthread -fsanitize=address
main_LDFLAGS=-m64 -L/home/luoyebai/.xmake/packages/g/gtest/v1.14.0/f970d73ab5f14d76aa4b780b603d9493/lib -lgtest -lgmock -lopencv_gapi -lopencv_stitching -lopencv_alphamat -lopencv_aruco -lopencv_bgsegm -lopencv_bioinspired -lopencv_ccalib -lopencv_cvv -lopencv_dnn_objdetect -lopencv_dnn_superres -lopencv_dpm -lopencv_face -lopencv_freetype -lopencv_fuzzy -lopencv_hdf -lopencv_hfs -lopencv_img_hash -lopencv_intensity_transform -lopencv_line_descriptor -lopencv_mcc -lopencv_quality -lopencv_rapid -lopencv_reg -lopencv_rgbd -lopencv_saliency -lopencv_signal -lopencv_stereo -lopencv_structured_light -lopencv_phase_unwrapping -lopencv_superres -lopencv_optflow -lopencv_surface_matching -lopencv_tracking -lopencv_highgui -lopencv_datasets -lopencv_text -lopencv_plot -lopencv_videostab -lopencv_videoio -lopencv_viz -lopencv_wechat_qrcode -lopencv_xfeatures2d -lopencv_shape -lopencv_ml -lopencv_ximgproc -lopencv_video -lopencv_xobjdetect -lopencv_objdetect -lopencv_calib3d -lopencv_imgcodecs -lopencv_features2d -lopencv_dnn -lopencv_flann -lopencv_xphoto -lopencv_photo -lopencv_imgproc -lopencv_core -lgtk-3 -lgdk-3 -lharfbuzz -lpangocairo-1.0 -lpango-1.0 -latk-1.0 -lcairo -lcairo-gobject -lgdk_pixbuf-2.0 -lgio-2.0 -lglib-2.0 -lgobject-2.0 -lavcodec -lavdevice -lavfilter -lavformat -lavutil -lpostproc -lswresample -lswscale -ldrm -lz -lpthread -fsanitize=address

default:  main

all:  main

.PHONY: default all  main

main: build/linux/x86_64/debug/main
build/linux/x86_64/debug/main: build/.objs/main/linux/x86_64/debug/src/config_reader.cpp.o build/.objs/main/linux/x86_64/debug/src/main.cpp.o build/.objs/main/linux/x86_64/debug/src/detector.cpp.o
	@echo linking.debug main
	@mkdir -p build/linux/x86_64/debug
	$(VV)$(main_LD) -o build/linux/x86_64/debug/main build/.objs/main/linux/x86_64/debug/src/config_reader.cpp.o build/.objs/main/linux/x86_64/debug/src/main.cpp.o build/.objs/main/linux/x86_64/debug/src/detector.cpp.o $(main_LDFLAGS)

build/.objs/main/linux/x86_64/debug/src/config_reader.cpp.o: src/config_reader.cpp
	@echo ccache compiling.debug src/config_reader.cpp
	@mkdir -p build/.objs/main/linux/x86_64/debug/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/debug/src/config_reader.cpp.o src/config_reader.cpp

build/.objs/main/linux/x86_64/debug/src/main.cpp.o: src/main.cpp
	@echo ccache compiling.debug src/main.cpp
	@mkdir -p build/.objs/main/linux/x86_64/debug/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/debug/src/main.cpp.o src/main.cpp

build/.objs/main/linux/x86_64/debug/src/detector.cpp.o: src/detector.cpp
	@echo ccache compiling.debug src/detector.cpp
	@mkdir -p build/.objs/main/linux/x86_64/debug/src
	$(VV)$(main_CXX) -c $(main_CXXFLAGS) -o build/.objs/main/linux/x86_64/debug/src/detector.cpp.o src/detector.cpp

clean:  clean_main

clean_main: 
	@rm -rf build/linux/x86_64/debug/main
	@rm -rf build/linux/x86_64/debug/main.sym
	@rm -rf build/.objs/main/linux/x86_64/debug/src/config_reader.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/debug/src/main.cpp.o
	@rm -rf build/.objs/main/linux/x86_64/debug/src/detector.cpp.o

